# Generated by Django 4.1.1 on 2022-09-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=256)),
                ('avatar', models.ImageField(upload_to='avatars/')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
