version: '3.1'

services:
  django:
    build: .
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    command: bash start.sh
    restart: always
    volumes:
      - .:/usr/local/src/presta
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
      - "nginx"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "7834:80"
    depends_on:
      - postgres

  nginx:
    image: "nginx:1.23"

  postgres:
    image: "postgres:14.5"
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'