# Use postgres/example user/password credentials
version: '3.1'

services:

  postgres:
    image: "postgres:14.5"
    restart: always
    environment:
      POSTGRES_DB: admin
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - '5432:5432'