version: '3.1'

services:
  django:
    build: .
    command: bash -c "
      python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000
      "
    restart: always
    volumes:
      - .:/usr/local/src/presta
    env_file:
      - .env.development
    ports:
      - "8080:8000"
    depends_on:
      - "postgres"
      - "nginx"

  nginx:
    image: "nginx:1.23"

  postgres:
    image: "postgres:14.5"
    restart: always
    env_file:
      - .env.development
    ports:
      - '5432:5432'