# Generated by Django 4.1.1 on 2022-09-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=20)),
                ('company_avatar', models.ImageField(upload_to='avatar/')),
                ('default_currency', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
