# Generated by Django 4.1.1 on 2022-09-15 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=60)),
                ('direction', models.CharField(max_length=80)),
                ('telephone_number', models.PositiveBigIntegerField()),
                ('telephone_ext', models.PositiveSmallIntegerField()),
                ('avatar', models.ImageField(upload_to='avatars/')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('due_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('interests', models.DecimalField(decimal_places=2, max_digits=3)),
                ('fee_type', models.PositiveSmallIntegerField()),
                ('start', models.DateField()),
                ('finish', models.DateField(null=True)),
                ('client', models.ManyToManyField(db_table='loans_clients', to='loans.client')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('measure_type', models.PositiveSmallIntegerField()),
                ('quantity', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('date', models.DateField()),
                ('delay', models.PositiveSmallIntegerField()),
                ('interests', models.PositiveSmallIntegerField()),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loan')),
                ('payment_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.paymenttime')),
            ],
        ),
        migrations.AddField(
            model_name='loan',
            name='payment_time',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loans.paymenttime'),
        ),
    ]
